### ISSUE TITLE
[PE-D][Tester D] Negative Infinity is a possible account value 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T15-2/tp#110]
![image.png](https://raw.githubusercontent.com/joshualeejunyi/ped/main/files/12f1961f-49e6-4f58-94bc-3d79c032ef77.png)

![image.png](https://raw.githubusercontent.com/joshualeejunyi/ped/main/files/118c9bc6-135c-4ea0-8546-0a315e635584.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: joshualeejunyi/ped#8

**Comment by vibes-863** [comment]
Thank you for reporting this. 

However, as mentioned in the 'Guidelines for determining bugs ' under 'Functionality Bugs' ([linked here](https://nus-cs2113-ay2324s2.github.io/website/schedule/week12/project.html#3-polish-the-deliverables)), this is an _extreme_ user behavior, and as it does not crash the app or corrupt the data, it is not considered a bug.
