### ISSUE TITLE
[Code Review] Vavinan

### ISSUE THREAD

**Issue by wwweert123** [AY2324S2-CS2113-T15-2/tp#43]
![image](https://github.com/AY2324S2-CS2113-T15-2/tp/assets/93811746/032697ce-3ef7-4a52-b9e7-dcc1d9cb4cc7)

Try not to say that the error is unknown, because in the PE all errors should be known and accounted for

![image](https://github.com/AY2324S2-CS2113-T15-2/tp/assets/93811746/06dd3a93-ee8c-4ad8-8889-7a8fa414b008)

In here, I don't think there is a need to check whether the data is a integer. This is because the Integer.parseInt method will automatically throw the number format exception if it fails

 
![image](https://github.com/AY2324S2-CS2113-T15-2/tp/assets/93811746/55b32a69-3010-45a9-bc92-54a1aace17c3)

You should add some error handling here because the user might access out-of-bounds for the splitted string "parts" 

Overall code looks organized but there are some parts where the function serve almost the same purpose as another. For example parseTransactionType and parseTransaction are the same except for the separator. Perhaps, more descriptive names can be used to differentiate the two or you could abstract the repeated logic out into another function.

**Comment by Vavinan** [comment]
1) It's for our debugging purpose to catch some unhandled error cases, we will remove that in our final product

2) We will consider this change in our future iterations

3) For this one the user input is received in way that it will prompt the user to type Transaction type first and then followed by other data one by one, where each data will be received separately. I have included the relevant function below. Correct me if I took the question wrongly. 

![Screenshot 2024-03-31 164148](https://github.com/AY2324S2-CS2113-T15-2/tp/assets/110589924/7193ca98-15f0-4258-89ad-44268ee6768e)


Thank you.

**Comment by wwweert123** [comment]
Ok understood, then this should be fine!

**Comment by wwweert123** [comment]
Oh and I missed out something, Is the category always an integer as well,? because you did parseInt() which might cause an uncaught exception to be thrown

**Comment by Vavinan** [comment]
Yes, it will be an integer always. For now, it has been caught if other numbers or text is typed instead. I have attached one example below. We will make a check explicitly in our future iterations. Thank you for notifying this.

![Screenshot 2024-03-31 171851](https://github.com/AY2324S2-CS2113-T15-2/tp/assets/110589924/b2d875bf-30c7-4cd5-8722-f8b3d7b62d87)
